<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6zjaajf\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6zjaajf/App_KernelProdContainer.php') {
    touch(__DIR__.'/Container6zjaajf.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\Container6zjaajf\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \Container6zjaajf\App_KernelProdContainer([
    'container.build_hash' => '6zjaajf',
    'container.build_id' => '521b3670',
    'container.build_time' => 1609753554,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6zjaajf');
